### ISSUE TITLE
Lockdown Deployment using Proxmox 

### ISSUE THREAD

**Issue by jay13patel** [ubnetdef/Lockdown-v8#1]
Can we deploy Lockdown Environment using Proxmox for practice sessions?

**Comment by Vasu-Baldwa** [comment]
You can! You'd need to configure Ansible to work with Proxmox. These links should provide a decent starting guide: https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_module.html
https://blog.dmcindoe.dev/posts/2021-07-31/automating-proxmox-with-ansible/

You'd also need the VM Templates. Currently we do not release these templates but you can pretty easily make your own.
